version: '3.8'
services:
  nginx:
    build: .
    # restart: always
    ports:
      - 80:80
  wiki:
    image: mediawiki
    restart: always
    volumes:
      - static:/var/www/html/
  wikiSQL:
    image: mysql
    restart: always
    volumes:
      - sql-data:/var/lib/mysql
  # mongo:
  #   image: mongo:7.0-rc3-jammy
  #   restart: always
  #   volumes:
  #     - mongo-data:/data/db
volumes:
  static:
  # mongo-data:
  sql-data:
networks:
  siteBridge:
    driver: bridge