version: '3.2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:./etc/nginx/nginx.conf
      - ./client/dist/:/var/www/html/
  mongo:
    image: mongo:7.0-rc3-jammy
    restart: always
    volumes:
      - mongodb:/data/db
  wiki:
    image: mediawiki
    restart: always
    volumes:
      - static:/var/ww/html/
  wikiSQL:
    image: mysql
    restart: always
    volumes:
      - sql:/var/lib/mysql
volumes:
  static:
  mongodb:
  sql:
networks:
  siteBridge:
    driver: bridge