version: '3.8'
services:
  wiki:
    container_name: landstrider_wiki
    # image: mediawiki:1.40
    build:
      context: .
      dockerfile: ./server/Wiki.Dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - static:/var/www/html/
      #- ./server/LocalSettings.php:/var/www/html/LocalSettings.php
    networks:
      - wiki
  wikiSQL:
    container_name: landstrider_sql
    image: mysql
    restart: always
    volumes:
      - sql-data:/var/lib/mysql
    env_file:
      - ./server/.env
    networks:
      - wiki
networks:
  wiki:
    driver: bridge
volumes:
  static:
  sql-data: