version: '3.2'
services:
  nginx:
    image: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./server/nginx.conf:./etc/nginx/nginx.conf
      - ./client/dist/:/var/www/html/
  mongo:
    image: mongo:7.0-rc3-jammy
    restart: always
    volumes:
      - mongodb:/data/db